fail scan

diff --git a/.github/workflows/build-scan-PR.yaml b/.github/workflows/build-scan-PR.yaml
--- a/.github/workflows/build-scan-PR.yaml
+++ b/.github/workflows/build-scan-PR.yaml
@@ -84,11 +84,25 @@ jobs:
           echo "scan_failed=$scan_failed" >> $GITHUB_OUTPUT
 
 
+
+      - name: Delete previous comments
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { data: comments } = await github.issues.listComments({...context.repo, issue_number: context.issue.number});
+            const comment = comments.find(comment => comment.user.type === "Bot" && comment.body.indexOf("Terrform update available") > -1);
+            if (comment) {
+              await github.issues.deleteComment({...context.repo, comment_id: comment.id});
+            }
+
+
       # Step to post a comment on the pull request with the scan results
       - name: Post scan results to PR
         if: steps.build_and_scan.outputs.scan_failed == 'true'
         uses: actions/github-script@v6
         with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             github.rest.issues.createComment({
               owner: context.repo.owner,
@@ -96,3 +110,11 @@ jobs:
               issue_number: context.issue.number,
               body: `### Vulnerability Scan Results\n${{steps.build_and_scan.outputs.scan_result}}`
             })
+
+
+      # Step to fail the action if scan_failed is true
+      - name: Fail action if scan failed
+        if: steps.build_and_scan.outputs.scan_failed == 'true'
+        run: |
+          echo "Scan failed due to CRITICAL vulnerabilities in one or more Dockerfiles."
+          exit 1
